# SETTINGS
[settings]
minimum_release_age = "3d"
minimum_release_age_excludes = ["pi"]

[settings.upgrade]
auto_prune = false

# ENV VARS
[env]

## Directories & Repositories
DOTS_DIR="/home/$USER/Dotfiles"

## Directories & Repositories
DOTS_PI_DIR="${DOTS_DIR}/pi-dots"
DOTS_PI_HTTPS='https://github.com/r3b1s/pi-dots'
DOTS_PI_SSH='git@github.com:r3b1s/pi-dots.git'

DOTS_OMARCHY_DIR="${DOTS_DIR}/omarchy-dots"
DOTS_OMARCHY_HTTPS='https://github.com/r3b1s/quattro-dots'
DOTS_OMARCHY_SSH='git@github.com:r3b1s/quattro-dots.git'

DOTS_ATHENA_DIR="${DOTS_DIR}/athena-dots"
DOTS_ATHENA_HTTPS='https://github.com/r3b1s/athena-dots'
DOTS_ATHENA_SSH='git@github.com:r3b1s/athena-dots.git'

## Pi default global cfg | Safety catch-all. Pi-derivative harnesses like oh-my-pi will clobber Pi's cfg files & sessions
PI_CODING_AGENT_DIR="/home/$USER/.pi/agent"

# TOOLS
[tools]
node = "latest"
uv = "latest"
age = "1.3.2"

## ai slop
pi = "latest"
"github:can1357/oh-my-pi" = "latest"
"npm:command-code" = "latest"
"npm:donsetch" = "latest"
agent-browser = "latest"

# TASKS

## Pull Dotfiles

### Pi
[tasks.dots-pull-pi]
description = "Clone athena dotfiles to local machine"
run = """
#!/usr/bin/env bash
cd "${DOTS_DIR}"
git clone "${DOTS_PI}"
cd "${DOTS_PI_DIR}"
git remote set-url origin "${DOTS_PI_SSH}"
"""

### omarchy
[tasks.dots-pull-omarchy]
description = "Clone omarchy dotfiles to local machine"
run = """
#!/usr/bin/env bash
mkdir -p "${DOTS_DIR}"
cd "${DOTS_DIR}"
git clone "${DOTS_OMARCHY}"
cd "${DOTS_OMARCHY_DIR}"
git remote set-url origin "${DOTS_OMARCHY_SSH}"
"""

### AthenaOS
[tasks.dots-pull-athena]
description = "Clone athena dotfiles to local machine"
run = """
#!/usr/bin/env bash
mkdir -p "${DOTS_DIR}"
cd "${DOTS_DIR}"
git clone "${DOTS_ATHENA}"
cd "${DOTS_ATHENA_DIR}"
git remote set-url origin "${DOTS_ATHENA_SSH}"
"""


## Pi Harness
[tasks.pi]
raw_args = true
dir = "{{cwd}}"
description = "Pi Vanilla"
run = 'PI_CODING_AGENT_DIR="${DOTS_PI_DIR}/agent" pi'

[tasks.pi-ctf]
raw_args = true
dir = "{{cwd}}"
description = "Pi CTF agent | Launch"
run = 'PI_CODING_AGENT_DIR="${DOTS_PI_DIR}/agent_ctf" pi --append-system-prompt "${PI_CODING_ADENT_DIR}/../system-prompts/append_ctf_0.md"'

[tasks.pi-ctf-install]
raw_args = true
dir = "{{cwd}}"
description = "Pi CTF agent | Install a plugin"
run = 'PI_CODING_AGENT_DIR="${DOTS_PI_DIR}/agent_ctf" pi install'

[tasks.pi-ctf-uninstall]
raw_args = true
dir = "{{cwd}}"
description = "Pi CTF agent | Install a plugin"
run = 'PI_CODING_AGENT_DIR="${DOTS_PI_DIR}/agent_ctf" pi remove'

## omp Harness
## - https://omp.sh/docs/env
[tasks.omp]
raw_args = true
dir = "{{cwd}}"
description = "omp Vanilla"
run = 'PI_CONFIG_DIR="~/.omp" PI_CODING_AGENT_DIR="~/.omp/agent" omp --cwd="."'

## CTF

[tasks.engagement-template]
dir = "{{cwd}}"
description = "Clone a CTF / engagement template to the cwd"
run = """
#!/usr/bin/env bash
templateUrl='https://github.com/r3b1s/engagement-template'
git clone ${templateUrl}
cd ${templateUrl}
rm -rf .git
"""


# [tasks.xyz]
# description = ""
# #!/usr/bin/env bash
# run = """
# """

## Other

### Scaffold Dirs
[tasks.scaffold-dirs]
description = "Scaffold common directories"
run = """
#!/usr/bin/env bash
mkdir -p \
  ~/tmp \
  ~/Dotfiles \
  ~/Engagements \
  ~/Projects \
  ~/Shared \
  ~/Machines \
  ~/3rdParty
"""

# [tasks.xyz]
# description = """
# run = """
# #!/usr/bin/env bash
# """
