# -------- SETTINGS --------- #
[settings]
minimum_release_age = "3d"
minimum_release_age_excludes = ["pi"]

[settings.upgrade]
auto_prune = false


# ----------- ENV ----------- #
[env]

## Editor
EDITOR='nvim'

## Directories & Repositories
DOTS_DIR="/home/$USER/Dotfiles"

## Directories & Repositories
DOTS_MISE_DIR="${DOTS_DIR}/mise-dots"
DOTS_MISE_HTTPS='https://github.com/r3b1s/mise-dots'
DOTS_MISE_SSH='git@github.com:r3b1s/mise-dots.git'

DOTS_PI_DIR="${DOTS_DIR}/pi-dots"
DOTS_PI_HTTPS='https://github.com/r3b1s/pi-dots'
DOTS_PI_SSH='git@github.com:r3b1s/pi-dots.git'

DOTS_OMARCHY_DIR="${DOTS_DIR}/quattro-dots"
DOTS_OMARCHY_HTTPS='https://github.com/r3b1s/quattro-dots'
DOTS_OMARCHY_SSH='git@github.com:r3b1s/quattro-dots.git'

DOTS_ATHENA_DIR="${DOTS_DIR}/athena-dots"
DOTS_ATHENA_HTTPS='https://github.com/r3b1s/athena-dots'
DOTS_ATHENA_SSH='git@github.com:r3b1s/athena-dots.git'

## Pi default global cfg | Safety catch-all. Pi-derivative harnesses like oh-my-pi will clobber Pi's cfg files & sessions
PI_CODING_AGENT_DIR="/home/$USER/.pi/agent"



# ---------- TOOLS ---------- #
[tools]
node = "latest"
uv = "latest"
age = "1.3.2"

## ai slop
pi = "latest"
"github:can1357/oh-my-pi" = "latest"
"npm:command-code" = "latest"
"npm:donsetch" = "latest"
agent-browser = "latest"
codex = "latest"
gh = "latest"



# ---------- TASKS ---------- #

## Dotfiles

### Setup Omarchy
[tasks.omarchy-dots-setup]
description = "Setup omarchy with personal dotfiles"
run = """
#!/usr/bin/env bash

# Ensure we are running on Omarchy
if [[ ! -r /etc/os-release ]]; then
  echo "Error: /etc/os-release not found; cannot verify OS." >&2
  exit 1
fi

. /etc/os-release
if [[ "${ID,,}" != "omarchy" && "${NAME,,}" != *omarchy* ]]; then
  echo "Error: this task requires Omarchy (detected: ${PRETTY_NAME:-${NAME:-unknown}})." >&2
  exit 1
fi

mkdir -p "${DOTS_DIR}"

# Omarchy
cd "${DOTS_DIR}"
git clone "${DOTS_OMARCHY_HTTPS}"
cd "${DOTS_OMARCHY_DIR}"
git remote set-url origin "${DOTS_OMARCHY_SSH}"
bash < "${DOTS_OMARCHY_DIR}/install.sh"

# Omarchy Pinkrot Theme
themename='omarchy-pinkrot-theme'
cd "${DOTS_DIR}"
git clone "https://github.com/r3b1s/${themename}.git"
cd "${themename}"
git remote set-url origin 'git@github.com:r3b1s/${themename}.git'
ln -s "${DOTS_DIR}/${themename}" "/home/$USER/.config/omarchy/themes/${themename}"

# Pi
cd "${DOTS_DIR}"
git clone "${DOTS_PI_HTTPS}"
cd "${DOTS_PI_DIR}"
git remote set-url origin "${DOTS_PI_SSH}"

# mise repo set-url to ssh
cd "${DOTS_MISE_DIR}"
git remote set-url origin "{DOTS_MISE_SSH}"
"""

### Setup Omarchy - https repos
[tasks.omarchy-dots-setup-https]
description = "Setup omarchy with personal dotfiles"
run = """
#!/usr/bin/env bash

# Ensure we are running on Omarchy
if [[ ! -r /etc/os-release ]]; then
  echo "Error: /etc/os-release not found; cannot verify OS." >&2
  exit 1
fi

. /etc/os-release
if [[ "${ID,,}" != "omarchy" && "${NAME,,}" != *omarchy* ]]; then
  echo "Error: this task requires Omarchy (detected: ${PRETTY_NAME:-${NAME:-unknown}})." >&2
  exit 1
fi

mkdir -p "${DOTS_DIR}"

# Omarchy
cd "${DOTS_DIR}"
git clone "${DOTS_OMARCHY_HTTPS}"
bash < "${DOTS_OMARCHY_DIR}/install.sh"

# Omarchy Pinkrot Theme
themename='omarchy-pinkrot-theme'
cd "${DOTS_DIR}"
git clone "https://github.com/r3b1s/${themename}.git"
ln -s "${DOTS_DIR}/${themename}" "/home/$USER/.config/omarchy/themes/${themename}"

# Pi
cd "${DOTS_DIR}"
git clone "${DOTS_PI_HTTPS}"
"""


### Omarchy Dots
[tasks.dclone-omarchy]
description = "Clone omarchy dotfiles to local machine"
run = """
#!/usr/bin/env bash
mkdir -p "${DOTS_DIR}"
cd "${DOTS_DIR}"
git clone "${DOTS_OMARCHY_HTTPS}"
cd "${DOTS_OMARCHY_DIR}"
git remote set-url origin "${DOTS_OMARCHY_SSH}"
"""

### AthenaOS Dots
[tasks.dclone-athena]
description = "Clone athena dotfiles to local machine"
run = """
#!/usr/bin/env bash
mkdir -p "${DOTS_DIR}"
cd "${DOTS_DIR}"
git clone "${DOTS_ATHENA_HTTPS}"
cd "${DOTS_ATHENA_DIR}"
git remote set-url origin "${DOTS_ATHENA_SSH}"
"""

### Pi Dots
[tasks.dclone-pi]
description = "Clone Pi dotfiles"
run = """
#!/usr/bin/env bash
cd "${DOTS_DIR}"
git clone "${DOTS_PI_HTTPS}"
cd "${DOTS_PI_DIR}"
git remote set-url origin "${DOTS_PI_SSH}"
"""

## Pi Harness
[tasks.pi]
raw_args = true
dir = "{{cwd}}"
description = "Pi Vanilla"
run = 'PI_CODING_AGENT_DIR="${DOTS_PI_DIR}/agent" pi'

[tasks.pi-ctf]
raw_args = true
dir = "{{cwd}}"
description = "Pi CTF agent | Launch"
run = 'PI_CODING_AGENT_DIR="${DOTS_PI_DIR}/agent_ctf" pi --append-system-prompt "${PI_CODING_ADENT_DIR}/../system-prompts/append_ctf_0.md"'

[tasks.pi-ctf-install]
raw_args = true
dir = "{{cwd}}"
description = "Pi CTF agent | Install a plugin"
run = 'PI_CODING_AGENT_DIR="${DOTS_PI_DIR}/agent_ctf" pi install'

[tasks.pi-ctf-uninstall]
raw_args = true
dir = "{{cwd}}"
description = "Pi CTF agent | Install a plugin"
run = 'PI_CODING_AGENT_DIR="${DOTS_PI_DIR}/agent_ctf" pi remove'

## omp Harness
## - https://omp.sh/docs/env
[tasks.omp]
raw_args = true
dir = "{{cwd}}"
description = "omp Vanilla"
run = 'PI_CONFIG_DIR="/home/$USER/.omp" PI_CODING_AGENT_DIR="/home/$USER/.omp/agent" omp'

## CTF

[tasks.engagement-template]
dir = "{{cwd}}"
description = "Clone a CTF / engagement template to the cwd"
run = """
#!/usr/bin/env bash
templateUrl='https://github.com/r3b1s/engagement-template'
git clone ${templateUrl}
cd ${templateUrl}
rm -rf .git
"""


# [tasks.xyz]
# description = ""
# #!/usr/bin/env bash
# run = """
# """

## Other

### Scaffold Dirs
[tasks.scaffold-dirs]
description = "Scaffold common directories"
run = """
#!/usr/bin/env bash
mkdir -p \
  ~/tmp \
  ~/Dotfiles \
  ~/Engagements \
  ~/Projects \
  ~/Shared \
  ~/Machines \
  ~/3rdParty
"""

# [tasks.xyz]
# description = """
# run = """
# #!/usr/bin/env bash
# """
